# -*- coding: utf-8 -*-
"""veg/fruit classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyqNehYG4A4_kwUtykICjvBXonnAt4ff
"""

from google.colab import files
uploaded = files.upload()

# Basic Libraries
import os
import numpy as np
import matplotlib.pyplot as plt

# TensorFlow & Keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam

# For Image Prediction
from tensorflow.keras.preprocessing import image

import zipfile

zip_path = "/content/validation.zip"   # Use the correct zip file name
extract_path = "data3" # yaha jaha extract karna hai

with zipfile.ZipFile('/content/validation.zip', 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzip ho gaya ")

import zipfile

zip_path = "/content/train.zip"   # Use the correct zip file name
extract_path = "data1" # yaha jaha extract karna hai

with zipfile.ZipFile('/content/train.zip', 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzip ho gaya ")

import zipfile

zip_path = "/content/test.zip"   # yaha apni zip file ka naam likho

extract_path = "data2" # yaha jaha extract karna hai

with zipfile.ZipFile('/content/test.zip', 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzip ho gaya ✅")

train_dir = "/content/data1"
val_dir = "/content/data3"

train_datagen = ImageDataGenerator(rescale=1./255)
val_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(100,100),
    batch_size=32,
    class_mode='categorical'
)

val_data = val_datagen.flow_from_directory(
    val_dir,
    target_size=(100,100),
    batch_size=32,
    class_mode='categorical')

data_train_path="/content/data1"
data_test_path = "/content/data2"
data_val_path = "/content/data3"

img_width = 180
img_height = 180

data_train = tf.keras.utils.image_dataset_from_directory(

data_train_path,

shuffle=True,

image_size=(img_width, img_height),

batch_size=32,

validation_split=False)

data_cat = data_train.class_names
print(data_cat)

data_val = tf.keras.utils.image_dataset_from_directory(data_val_path,

                                                  image_size=(img_height,img_width),

                                                  batch_size=32,

                                                  shuffle=False,

                                                  validation_split=False)

data_test = tf.keras.utils.image_dataset_from_directory(

data_test_path,

image_size=(img_height,img_width),

shuffle=False,

batch_size=32,

)

validation_split=False

plt.figure(figsize=(10,10))
for image, labels in data_train.take(1):
 for i in range(9):
   plt.subplot(3,3,i+1)
   plt.imshow(image[i].numpy().astype('uint8'))
   plt.title(data_cat[labels[i]])
   plt.axis('off')

from tensorflow.keras.models import Sequential

data_train

from tensorflow.keras import layers
 model = Sequential([

    layers.Rescaling(1./255),

    layers.Conv2D(16, 3, padding='same', activation='relu'),

    layers.MaxPooling2D(),

    layers.Conv2D(32,3, padding='same', activation= 'relu'),

    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, padding='same', activation ='relu'),

    layers.MaxPooling2D(),

    layers.Flatten(),

    layers.Dropout (0.2),

    layers.Dense(128),

    layers.Dense(len(data_cat))
])

model.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

epochs_size = 10 # Define epochs_size
history = model.fit(data_train, validation_data=data_val, epochs=epochs_size)
if 'history' in locals() or 'history' in globals():
    epochs_range = range(epochs_size)

    plt.figure(figsize=(8,8))

    plt.subplot(1,2,1)

    plt.plot(epochs_range,history.history['accuracy'],label = 'Training Accuracy')

    plt.plot(epochs_range,history.history['val_accuracy'],label= 'Validation Accuracy')

    plt.title('Accuracy')

    plt.subplot(1,2,2)

    plt.plot(epochs_range, history.history['loss'],label ='Training loss')

    plt.plot(epochs_range, history.history['val_loss'],label = 'Validation loss')

    plt.title('loss')
else:
    print("Error: 'history' object not found. Please train the model first to generate training history.")

model = tf.keras.models.load_model("/content/drive/MyDrive/VegFruitProject/veg_fruit_model.h5")

image = '/content/data3/apple/Image_10.jpg'
image = tf.keras.utils.load_img(image, target_size=(img_height,img_width))
img_arr = tf.keras.utils.img_to_array(image)
img_bat= tf.expand_dims(img_arr,0)

predict = model.predict(img_bat)

score = tf.nn.softmax(predict)

__builtins__.print(f"Fruit Freshness in image is {data_cat[np.argmax(score)]} "
      f"with accuracy of {np.max(score)*100:.2f}%")

model.save('Image_classifly.keras')

from google.colab import drive
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/VegFruitProject/veg_fruit_model.h5")